/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { a as three } from "@react-spring/three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube008: THREE.Mesh;
    Cube008_1: THREE.Mesh;
    Cube008_2: THREE.Mesh;
    touchbar: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube002_1: THREE.Mesh;
    keyboard: THREE.Mesh;
  };
  materials: {
    aluminium: THREE.MeshStandardMaterial;
    ["matte.001"]: THREE.MeshStandardMaterial;
    ["screen.001"]: THREE.MeshStandardMaterial;
    touchbar: THREE.MeshStandardMaterial;
    trackpad: THREE.MeshStandardMaterial;
    keys: THREE.MeshStandardMaterial;
  };
};

export function Model({ open, hinge, ...props }) {
  const group = useRef<THREE.Group>();

  const [hovered, setHovered] = useState<boolean>(false);

  useEffect(
    () => void (document.body.style.cursor = hovered ? "pointer" : "auto"),
    [hovered]
  );

  // Make it float in the air when it's opened
  useFrame(state => {
    const t = state.clock.getElapsedTime();
    group.current.rotation.x = THREE.MathUtils.lerp(
      group.current.rotation.x,
      open ? Math.cos(t / 10) / 10 + 0.25 : 0,
      0.1
    );
    group.current.rotation.y = THREE.MathUtils.lerp(
      group.current.rotation.y,
      open ? Math.sin(t / 10) / 4 : 0,
      0.1
    );
    group.current.rotation.z = THREE.MathUtils.lerp(
      group.current.rotation.z,
      open ? Math.sin(t / 10) / 10 : 0,
      0.1
    );
    group.current.position.y = THREE.MathUtils.lerp(
      group.current.position.y,
      open ? (-2 + Math.sin(t)) / 3 : -4.3,
      0.1
    );
  });

  const { nodes, materials } = useGLTF("/mac-draco.glb") as GLTFResult;
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onPointerOver={e => (e.stopPropagation(), setHovered(true))}
      onPointerOut={e => setHovered(false)}
    >
      <three.group
        rotateX={hinge}
        position={[0, 0, 0.41]}
        rotation={[0.01, Math.PI, 0]}
      >
        <group position={[0, 2.96, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube008.geometry}
            material={materials.aluminium}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube008_1.geometry}
            material={materials["matte.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube008_2.geometry}
            material={materials["screen.001"]}
          />
        </group>
      </three.group>
      <three.group rotation={[0, Math.PI, 0]} position={[0, 0, 0.9]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.touchbar.geometry}
          material={materials.touchbar}
          position={[0, -0.03, 1.2]}
        />
        <group position={[0, -0.1, 3.39]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={materials.aluminium}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={materials.trackpad}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.keyboard.geometry}
          material={materials.keys}
          position={[1.79, 0, 3.45]}
        />
      </three.group>
    </group>
  );
}

useGLTF.preload("/mac-draco.glb");
